rm -rf Risultati/*gofr*
rm -rf Risultati/*gave*
rm -rf Risultati/*epot*
rm -rf Risultati/*pres*
rm -rf *gofr*
rm -rf *gave*
rm -rf *epot*
rm -rf *pres*
rm -rf frames/*.xyz
rm -rf seed.out
rm -rf config.final
